version: "3"
services:
  apache: 
    container_name: apache-proxy
    image: ${ENV_APACHE_IMAGE} 
    ports: 
      - "80:80" 
    environment: 
      - "TZ:America/Detroit" 
    volumes:
      - ${ENV_WEB}:/var/www/html